# Generated by Django 3.2.13 on 2023-02-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('startingBid', models.IntegerField()),
                ('imageURL', models.URLField(max_length=500, null=True)),
                ('category', models.CharField(choices=[('a', 'foo'), ('b', 'bar')], max_length=64, null=True)),
            ],
        ),
    ]
