# Generated by Django 3.2.13 on 2023-02-21 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20230221_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='CategoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='imageURL',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
