# Generated by Django 3.2.13 on 2023-02-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20230221_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='currentBid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
